apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: nginx
data:
  fluent.conf: |
    <source>
        @type tail
        path /var/log/nginx/access.log
        tag nginx.access
        format nginx
    </source>
    <match nginx.access>
      @type stdout
    </match>
