apiVersion: v1
kind: Service
metadata:
  name: fluent-service
  namespace: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: fluentd
    port: 24224
    targetPort: 24224
    nodePort: 30224
